name: Publish

on:
  release:
    types:
      - "published"
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: 'Tag name that the major tag will point to'
        required: true

env:
  TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}

permissions:
  contents: read

jobs:
  # TODO: Use caching?
  build_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.TAG_NAME }}
      - name: Log in to Heroku
        run: make reg-login
        env:
          HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN }} 
      - name: Image Build
        run: make image-build
      - name: Image Push
        run: |
          make image-push
          IMG_ID=$(make image-id-silent)
          echo $IMG_ID > ./IMG_ID.txt
      - name: Save IMG_ID
        uses: actions/upload-artifact@v3
        with:
          name: IMG_ID
          path: ./IMG_ID.txt
